[font]
size = 14.0

[font.normal]
family = "Inconsolata LGC Nerd Font Mono"

[window]
opacity = 1

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#2D2A2E"
foreground = "#fff1f3"

[colors.normal]
black = "#2c2525"
red = "#fd6883"
green = "#adda78"
yellow = "#f9cc6c"
blue = "#a8a9eb"
magenta = "#f38d70"
cyan = "#85dacc"
white = "#fff1f3"

[colors.bright]
black = "#72696a"
red = "#fd6883"
green = "#adda78"
yellow = "#f9cc6c"
blue = "#a8a9eb"
magenta = "#f38d70"
cyan = "#85dacc"
white = "#fff1f3"
