"$schema" = 'https://starship.rs/config-schema.json'

format = '''$git_branch $git_status${custom.git_newline}$python$nix_shell$shlvl $directory $character'''

scan_timeout = 30

[directory]
style = 'bold white'
truncation_length = 100
truncate_to_repo = false
format = '[$path]($style)'
disabled = false

[git_branch]
always_show_remote = true
format = " [$branch(:$remote_branch)]($style)"
style = 'bold blue'
disabled = false

[git_status]
format = "$untracked$modified$staged$renamed$deleted$ahead_behind$stashed$conflicted"
untracked  = '([U:$count](bold white) )'
modified   = '([M:$count](bold green) )'
staged     = '([S:$count](bold yellow) )'
renamed    = '([R:$count](bold blue) )'
deleted    = '([D:$count](bold red) )'
ahead      = '([A:$count](bold green) )'
behind     = '([B:$count](bold blue) )'
stashed    = '([S:$count](bold yellow) )'
conflicted = '([C:$count](bold red) )'
disabled = false

[character]
success_symbol = '[>](white)'
vimcmd_symbol = '[<](white)'
error_symbol = '[>](white)'

[line_break]
format = "\n"

[python]
format = '(\[py:$virtualenv\] )'
disabled = false

[nix_shell]
format = '(\[nix:$name\]) '
disabled = false
heuristic = true

[shlvl]
format = '\[$shlvl\]'
disabled = false
threshold = 2

[custom.git_newline]
command = 'echo ""'
when = 'git rev-parse --is-inside-work-tree 2>/dev/null'
format = "$output\n"
