#!/bin/sh

# System

export SYSTEM_DIR="$HOME/System"

# XDG Paths

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# Path

export PATH="$SYSTEM_DIR/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# GTK

export XCURSOR_THEME="Bibata-Modern-Classic"

# Applications

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"
export FILE_MANAGER="pcmanfm"
export CLI_FILE_MANAGER="lf"
export PDF_VIEWER="zathura"
export IMAGE_VIEWER="imv"
export VIDEO_VIEWER="mpv"
export WORD_EDITOR="libreoffice"
export PRESENTATION_EDITOR="libreoffice"
export SPREADSHEET_EDITOR="libreoffice"
export MANPAGER="nvim +Man!"

# fd

export FD_IGNORE="$XDG_CONFIG_HOME/fd/ignore"

# fzf

source <(fzf --zsh)
export FZF_KEYBINDINGS="alt-j:down,alt-k:up,alt-l:accept,alt-h:cancel,alt-space:toggle"
export FZF_DEFAULT_OPTS="--bind=$FZF_KEYBINDINGS"
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --color bg:#080808 \
  --color bg+:#262626 \
  --color border:#2e2e2e \
  --color fg:#b2b2b2 \
  --color fg+:#e4e4e4 \
  --color gutter:#262626 \
  --color header:#80a0ff \
  --color hl+:#f09479 \
  --color hl:#f09479 \
  --color info:#cfcfb0 \
  --color marker:#f09479 \
  --color pointer:#ff5189 \
  --color prompt:#80a0ff \
  --color spinner:#36c692
"

# git

export GIT_CONFIG_GLOBAL="$XDG_CONFIG_HOME/git/.gitconfig"

# rust

export RUSTUP_HOME="$XDG_CONFIG_HOME/rustup"
export CARGO_HOME="$XDG_CONFIG_HOME/cargo"
export PATH="$CARGO_HOME/bin:$PATH"

# starship

export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"

# xsecurelock

export XSECURELOCK_BLANK_DPMS_STATE="off"
export XSECURELOCK_FONT="Inconsolata LGC Nerd Font Mono"
export XSECURELOCK_SHOW_DATETIME="1"

# bun

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# sops

export SOPS_AGE_KEY_FILE="$HOME/Sops/age/keys.txt"
