# History

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=$XDG_CACHE_HOME/zsh/history
mkdir -p "$(dirname "$HISTFILE")"
setopt appendhistory
setopt inc_append_history

# Colors

autoload -U colors && colors

# Basic auto/tab complete:

autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# Use vim keys in tab complete menu:

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M vicmd 'e' edit-command-line
bindkey -v '^?' backward-delete-char
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# Edit line in vim with ctrl-e:

autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# Aliases

alias ls='eza -lh --color=auto'
alias lf='lfcd'
alias valgrind-check='valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes'

# fzf

source <(fzf --zsh)

# Starship

eval "$(starship init zsh)"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"

# Tmux

TPM_DIR="$HOME/.tmux/plugins/tpm"

if [ ! -d "$TPM_DIR" ]; then
  echo "TPM not found. Cloning Tmux Plugin Manager..."
  git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"
fi

# Cargo

[[ -f "$CARGO_HOME/env" ]] && . "$CARGO_HOME/env"

# lf

lfcd () {
    tmp="$(mktemp)"
    lfrun -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}

if [ -f /tmp/lf_cd ]; then
  source /tmp/lf_cd
  rm /tmp/lf_cd
fi

# zsh syntax hilighting

if [ -f $XDG_DATA_HOME/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source $XDG_DATA_HOME/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

fpath+=~/.zfunc; autoload -Uz compinit; compinit
