# History

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history
setopt appendhistory
setopt inc_append_history

# Colors

autoload -U colors && colors

# Basic auto/tab complete:

autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# Use vim keys in tab complete menu:

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M vicmd 'e' edit-command-line
bindkey -v '^?' backward-delete-char
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# Edit line in vim with ctrl-e:

autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# Aliases

[ -f "$ZDOTDIR/aliasrc" ] && source "$ZDOTDIR/aliasrc"

# Environment

[ -f "$ZDOTDIR/envrc" ] && source "$ZDOTDIR/envrc"

# Starship

eval "$(starship init zsh)"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"

# Tmux

TPM_DIR="$HOME/.tmux/plugins/tpm"

if [ ! -d "$TPM_DIR" ]; then
  echo "TPM not found. Cloning Tmux Plugin Manager..."
  git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"
fi

# lf

lfcd () {
    tmp="$(mktemp)"
    lfrun -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}

if [ -f /tmp/lf_cd ]; then
  source /tmp/lf_cd
  rm /tmp/lf_cd
fi

# fzf

source <(fzf --zsh)
export FZF_KEYBINDINGS="alt-j:down,alt-k:up,alt-l:accept,alt-h:cancel,alt-space:toggle"
export FZF_DEFAULT_OPTS="--bind=$FZF_KEYBINDINGS"
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --color bg:#080808 \
  --color bg+:#262626 \
  --color border:#2e2e2e \
  --color fg:#b2b2b2 \
  --color fg+:#e4e4e4 \
  --color gutter:#262626 \
  --color header:#80a0ff \
  --color hl+:#f09479 \
  --color hl:#f09479 \
  --color info:#cfcfb0 \
  --color marker:#f09479 \
  --color pointer:#ff5189 \
  --color prompt:#80a0ff \
  --color spinner:#36c692
"

# fd

export FD_IGNORE="$HOME/.config/fd/ignore"

# bun

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# sops

export SOPS_AGE_KEY_FILE="$HOME/Sops/age/keys.txt"

# zsh syntax hilighting

if [ -f ~/.local/share/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source ~/.local/share/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# ~/.local/bin
export PATH="$HOME/.local/bin:$PATH"

fpath+=~/.zfunc; autoload -Uz compinit; compinit
